import { BatchExecuteStatementCommandInput, BatchExecuteStatementCommandOutput, BatchGetItemCommandInput, BatchGetItemCommandOutput, BatchWriteItemCommandInput, BatchWriteItemCommandOutput, CreateBackupCommandInput, CreateBackupCommandOutput, CreateGlobalTableCommandInput, CreateGlobalTableCommandOutput, CreateTableCommandInput, CreateTableCommandOutput, DeleteBackupCommandInput, DeleteBackupCommandOutput, DeleteItemCommandInput, DeleteItemCommandOutput, DeleteTableCommandInput, DeleteTableCommandOutput, DescribeBackupCommandInput, DescribeBackupCommandOutput, DescribeContinuousBackupsCommandInput, DescribeContinuousBackupsCommandOutput, DescribeContributorInsightsCommandInput, DescribeContributorInsightsCommandOutput, DescribeEndpointsCommandInput, DescribeEndpointsCommandOutput, DescribeExportCommandInput, DescribeExportCommandOutput, DescribeGlobalTableCommandInput, DescribeGlobalTableCommandOutput, DescribeGlobalTableSettingsCommandInput, DescribeGlobalTableSettingsCommandOutput, DescribeKinesisStreamingDestinationCommandInput, DescribeKinesisStreamingDestinationCommandOutput, DescribeLimitsCommandInput, DescribeLimitsCommandOutput, DescribeTableCommandInput, DescribeTableCommandOutput, DescribeTableReplicaAutoScalingCommandInput, DescribeTableReplicaAutoScalingCommandOutput, DescribeTimeToLiveCommandInput, DescribeTimeToLiveCommandOutput, DisableKinesisStreamingDestinationCommandInput, DisableKinesisStreamingDestinationCommandOutput, EnableKinesisStreamingDestinationCommandInput, EnableKinesisStreamingDestinationCommandOutput, ExecuteStatementCommandInput, ExecuteStatementCommandOutput, ExecuteTransactionCommandInput, ExecuteTransactionCommandOutput, ExportTableToPointInTimeCommandInput, ExportTableToPointInTimeCommandOutput, GetItemCommandInput, GetItemCommandOutput, ListBackupsCommandInput, ListBackupsCommandOutput, ListContributorInsightsCommandInput, ListContributorInsightsCommandOutput, ListExportsCommandInput, ListExportsCommandOutput, ListGlobalTablesCommandInput, ListGlobalTablesCommandOutput, ListTablesCommandInput, ListTablesCommandOutput, ListTagsOfResourceCommandInput, ListTagsOfResourceCommandOutput, PutItemCommandInput, PutItemCommandOutput, QueryCommandInput, QueryCommandOutput, RestoreTableFromBackupCommandInput, RestoreTableFromBackupCommandOutput, RestoreTableToPointInTimeCommandInput, RestoreTableToPointInTimeCommandOutput, ScanCommandInput, ScanCommandOutput, TagResourceCommandInput, TagResourceCommandOutput, TransactGetItemsCommandInput, TransactGetItemsCommandOutput, TransactWriteItemsCommandInput, TransactWriteItemsCommandOutput, UntagResourceCommandInput, UntagResourceCommandOutput, UpdateContinuousBackupsCommandInput, UpdateContinuousBackupsCommandOutput, UpdateContributorInsightsCommandInput, UpdateContributorInsightsCommandOutput, UpdateGlobalTableCommandInput, UpdateGlobalTableCommandOutput, UpdateGlobalTableSettingsCommandInput, UpdateGlobalTableSettingsCommandOutput, UpdateItemCommandInput, UpdateItemCommandOutput, UpdateTableCommandInput, UpdateTableCommandOutput, UpdateTableReplicaAutoScalingCommandInput, UpdateTableReplicaAutoScalingCommandOutput, UpdateTimeToLiveCommandInput, UpdateTimeToLiveCommandOutput, DynamoDB } from '@aws-sdk/client-dynamodb';
import { Observable } from 'rxjs';
import { ObservableDynamoDBClient } from './ObservableDynamoDBClient';
export declare type BatchExecuteStatementCommandOptions = Parameters<InstanceType<typeof DynamoDB>['batchExecuteStatement']>[1];
export declare type BatchGetItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['batchGetItem']>[1];
export declare type BatchWriteItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['batchWriteItem']>[1];
export declare type CreateBackupCommandOptions = Parameters<InstanceType<typeof DynamoDB>['createBackup']>[1];
export declare type CreateGlobalTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['createGlobalTable']>[1];
export declare type CreateTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['createTable']>[1];
export declare type DeleteBackupCommandOptions = Parameters<InstanceType<typeof DynamoDB>['deleteBackup']>[1];
export declare type DeleteItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['deleteItem']>[1];
export declare type DeleteTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['deleteTable']>[1];
export declare type DescribeBackupCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeBackup']>[1];
export declare type DescribeContinuousBackupsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeContinuousBackups']>[1];
export declare type DescribeContributorInsightsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeContributorInsights']>[1];
export declare type DescribeEndpointsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeEndpoints']>[1];
export declare type DescribeExportCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeExport']>[1];
export declare type DescribeGlobalTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeGlobalTable']>[1];
export declare type DescribeGlobalTableSettingsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeGlobalTableSettings']>[1];
export declare type DescribeKinesisStreamingDestinationCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeKinesisStreamingDestination']>[1];
export declare type DescribeLimitsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeLimits']>[1];
export declare type DescribeTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeTable']>[1];
export declare type DescribeTableReplicaAutoScalingCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeTableReplicaAutoScaling']>[1];
export declare type DescribeTimeToLiveCommandOptions = Parameters<InstanceType<typeof DynamoDB>['describeTimeToLive']>[1];
export declare type DisableKinesisStreamingDestinationCommandOptions = Parameters<InstanceType<typeof DynamoDB>['disableKinesisStreamingDestination']>[1];
export declare type EnableKinesisStreamingDestinationCommandOptions = Parameters<InstanceType<typeof DynamoDB>['enableKinesisStreamingDestination']>[1];
export declare type ExecuteStatementCommandOptions = Parameters<InstanceType<typeof DynamoDB>['executeStatement']>[1];
export declare type ExecuteTransactionCommandOptions = Parameters<InstanceType<typeof DynamoDB>['executeTransaction']>[1];
export declare type ExportTableToPointInTimeCommandOptions = Parameters<InstanceType<typeof DynamoDB>['exportTableToPointInTime']>[1];
export declare type GetItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['getItem']>[1];
export declare type ListBackupsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listBackups']>[1];
export declare type ListContributorInsightsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listContributorInsights']>[1];
export declare type ListExportsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listExports']>[1];
export declare type ListGlobalTablesCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listGlobalTables']>[1];
export declare type ListTablesCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listTables']>[1];
export declare type ListTagsOfResourceCommandOptions = Parameters<InstanceType<typeof DynamoDB>['listTagsOfResource']>[1];
export declare type PutItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['putItem']>[1];
export declare type QueryCommandOptions = Parameters<InstanceType<typeof DynamoDB>['query']>[1];
export declare type RestoreTableFromBackupCommandOptions = Parameters<InstanceType<typeof DynamoDB>['restoreTableFromBackup']>[1];
export declare type RestoreTableToPointInTimeCommandOptions = Parameters<InstanceType<typeof DynamoDB>['restoreTableToPointInTime']>[1];
export declare type ScanCommandOptions = Parameters<InstanceType<typeof DynamoDB>['scan']>[1];
export declare type TagResourceCommandOptions = Parameters<InstanceType<typeof DynamoDB>['tagResource']>[1];
export declare type TransactGetItemsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['transactGetItems']>[1];
export declare type TransactWriteItemsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['transactWriteItems']>[1];
export declare type UntagResourceCommandOptions = Parameters<InstanceType<typeof DynamoDB>['untagResource']>[1];
export declare type UpdateContinuousBackupsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateContinuousBackups']>[1];
export declare type UpdateContributorInsightsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateContributorInsights']>[1];
export declare type UpdateGlobalTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateGlobalTable']>[1];
export declare type UpdateGlobalTableSettingsCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateGlobalTableSettings']>[1];
export declare type UpdateItemCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateItem']>[1];
export declare type UpdateTableCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateTable']>[1];
export declare type UpdateTableReplicaAutoScalingCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateTableReplicaAutoScaling']>[1];
export declare type UpdateTimeToLiveCommandOptions = Parameters<InstanceType<typeof DynamoDB>['updateTimeToLive']>[1];
export declare class ObservableDynamoDB extends ObservableDynamoDBClient {
    batchExecuteStatement(args: BatchExecuteStatementCommandInput, options?: BatchExecuteStatementCommandOptions): Observable<BatchExecuteStatementCommandOutput>;
    batchGetItem(args: BatchGetItemCommandInput, options?: BatchGetItemCommandOptions): Observable<BatchGetItemCommandOutput>;
    createBackup(args: CreateBackupCommandInput, options?: CreateBackupCommandOptions): Observable<CreateBackupCommandOutput>;
    batchWriteItem(args: BatchWriteItemCommandInput, options?: BatchWriteItemCommandOptions): Observable<BatchWriteItemCommandOutput>;
    createGlobalTable(args: CreateGlobalTableCommandInput, options?: CreateGlobalTableCommandOptions): Observable<CreateGlobalTableCommandOutput>;
    createTable(args: CreateTableCommandInput, options?: CreateTableCommandOptions): Observable<CreateTableCommandOutput>;
    deleteBackup(args: DeleteBackupCommandInput, options?: DeleteBackupCommandOptions): Observable<DeleteBackupCommandOutput>;
    deleteItem(args: DeleteItemCommandInput, options?: DeleteItemCommandOptions): Observable<DeleteItemCommandOutput>;
    deleteTable(args: DeleteTableCommandInput, options?: DeleteTableCommandOptions): Observable<DeleteTableCommandOutput>;
    describeBackup(args: DescribeBackupCommandInput, options?: DescribeBackupCommandOptions): Observable<DescribeBackupCommandOutput>;
    describeContinuousBackups(args: DescribeContinuousBackupsCommandInput, options?: DescribeContinuousBackupsCommandOptions): Observable<DescribeContinuousBackupsCommandOutput>;
    describeContributorInsights(args: DescribeContributorInsightsCommandInput, options?: DescribeContributorInsightsCommandOptions): Observable<DescribeContributorInsightsCommandOutput>;
    describeEndpoints(args: DescribeEndpointsCommandInput, options?: DescribeEndpointsCommandOptions): Observable<DescribeEndpointsCommandOutput>;
    describeExport(args: DescribeExportCommandInput, options?: DescribeExportCommandOptions): Observable<DescribeExportCommandOutput>;
    describeGlobalTable(args: DescribeGlobalTableCommandInput, options?: DescribeGlobalTableCommandOptions): Observable<DescribeGlobalTableCommandOutput>;
    describeGlobalTableSettings(args: DescribeGlobalTableSettingsCommandInput, options?: DescribeGlobalTableSettingsCommandOptions): Observable<DescribeGlobalTableSettingsCommandOutput>;
    describeKinesisStreamingDestination(args: DescribeKinesisStreamingDestinationCommandInput, options?: DescribeKinesisStreamingDestinationCommandOptions): Observable<DescribeKinesisStreamingDestinationCommandOutput>;
    describeLimits(args: DescribeLimitsCommandInput, options?: DescribeLimitsCommandOptions): Observable<DescribeLimitsCommandOutput>;
    describeTable(args: DescribeTableCommandInput, options?: DescribeTableCommandOptions): Observable<DescribeTableCommandOutput>;
    describeTableReplicaAutoScaling(args: DescribeTableReplicaAutoScalingCommandInput, options?: DescribeTableReplicaAutoScalingCommandOptions): Observable<DescribeTableReplicaAutoScalingCommandOutput>;
    describeTimeToLive(args: DescribeTimeToLiveCommandInput, options?: DescribeTimeToLiveCommandOptions): Observable<DescribeTimeToLiveCommandOutput>;
    disableKinesisStreamingDestination(args: DisableKinesisStreamingDestinationCommandInput, options?: DisableKinesisStreamingDestinationCommandOptions): Observable<DisableKinesisStreamingDestinationCommandOutput>;
    enableKinesisStreamingDestination(args: EnableKinesisStreamingDestinationCommandInput, options?: EnableKinesisStreamingDestinationCommandOptions): Observable<EnableKinesisStreamingDestinationCommandOutput>;
    executeStatement(args: ExecuteStatementCommandInput, options?: ExecuteStatementCommandOptions): Observable<ExecuteStatementCommandOutput>;
    executeTransaction(args: ExecuteTransactionCommandInput, options?: ExecuteTransactionCommandOptions): Observable<ExecuteTransactionCommandOutput>;
    exportTableToPointInTime(args: ExportTableToPointInTimeCommandInput, options?: ExportTableToPointInTimeCommandOptions): Observable<ExportTableToPointInTimeCommandOutput>;
    getItem(args: GetItemCommandInput, options?: GetItemCommandOptions): Observable<GetItemCommandOutput>;
    listBackups(args: ListBackupsCommandInput, options?: ListBackupsCommandOptions): Observable<ListBackupsCommandOutput>;
    listContributorInsights(args: ListContributorInsightsCommandInput, options?: ListContributorInsightsCommandOptions): Observable<ListContributorInsightsCommandOutput>;
    listExports(args: ListExportsCommandInput, options?: ListExportsCommandOptions): Observable<ListExportsCommandOutput>;
    listGlobalTables(args: ListGlobalTablesCommandInput, options?: ListGlobalTablesCommandOptions): Observable<ListGlobalTablesCommandOutput>;
    listTables(args: ListTablesCommandInput, options?: ListTablesCommandOptions): Observable<ListTablesCommandOutput>;
    listTagsOfResource(args: ListTagsOfResourceCommandInput, options?: ListTagsOfResourceCommandOptions): Observable<ListTagsOfResourceCommandOutput>;
    putItem(args: PutItemCommandInput, options?: PutItemCommandOptions): Observable<PutItemCommandOutput>;
    query(args: QueryCommandInput, options?: QueryCommandOptions): Observable<QueryCommandOutput>;
    restoreTableFromBackup(args: RestoreTableFromBackupCommandInput, options?: RestoreTableFromBackupCommandOptions): Observable<RestoreTableFromBackupCommandOutput>;
    restoreTableToPointInTime(args: RestoreTableToPointInTimeCommandInput, options?: RestoreTableToPointInTimeCommandOptions): Observable<RestoreTableToPointInTimeCommandOutput>;
    scan(args: ScanCommandInput, options?: ScanCommandOptions): Observable<ScanCommandOutput>;
    tagResource(args: TagResourceCommandInput, options?: TagResourceCommandOptions): Observable<TagResourceCommandOutput>;
    transactGetItems(args: TransactGetItemsCommandInput, options?: TransactGetItemsCommandOptions): Observable<TransactGetItemsCommandOutput>;
    transactWriteItems(args: TransactWriteItemsCommandInput, options?: TransactWriteItemsCommandOptions): Observable<TransactWriteItemsCommandOutput>;
    untagResource(args: UntagResourceCommandInput, options?: UntagResourceCommandOptions): Observable<UntagResourceCommandOutput>;
    updateContinuousBackups(args: UpdateContinuousBackupsCommandInput, options?: UpdateContinuousBackupsCommandOptions): Observable<UpdateContinuousBackupsCommandOutput>;
    updateContributorInsights(args: UpdateContributorInsightsCommandInput, options?: UpdateContributorInsightsCommandOptions): Observable<UpdateContributorInsightsCommandOutput>;
    updateGlobalTable(args: UpdateGlobalTableCommandInput, options?: UpdateGlobalTableCommandOptions): Observable<UpdateGlobalTableCommandOutput>;
    updateGlobalTableSettings(args: UpdateGlobalTableSettingsCommandInput, options?: UpdateGlobalTableSettingsCommandOptions): Observable<UpdateGlobalTableSettingsCommandOutput>;
    updateItem(args: UpdateItemCommandInput, options?: UpdateItemCommandOptions): Observable<UpdateItemCommandOutput>;
    updateTable(args: UpdateTableCommandInput, options?: UpdateTableCommandOptions): Observable<UpdateTableCommandOutput>;
    updateTableReplicaAutoScaling(args: UpdateTableReplicaAutoScalingCommandInput, options?: UpdateTableReplicaAutoScalingCommandOptions): Observable<UpdateTableReplicaAutoScalingCommandOutput>;
    updateTimeToLive(args: UpdateTimeToLiveCommandInput, options?: UpdateTimeToLiveCommandOptions): Observable<UpdateTimeToLiveCommandOutput>;
    destroy(): void;
}
